### PR TITLE
Pull in upstream updates from cisagov/skeleton-ansible-role

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

In this pull request I pull in the upstream updates from [cisagov/skeleton-ansible-role](https://github.com/cisagov/skeleton-ansible-role).

## 💭 Motivation and Context

I'm going to be making changes to this repository, so I may as well make sure it is up to date.

## 🧪 Testing

All pre-commit hooks and GitHub Actions pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — COMMENTED** [review]
Looks good so far, but no approval until the molecule tests all pass.

**Review by felddy — APPROVED** [review]
Looks good.  I'm confident that when the tests pass this will still be a good PR.  
👍

**Comment by jsf9k** [comment]
All the checks pass now, except for the BS JS LGTM check that insists on launching for no reason.  @dav3r and @mcdonnnj, you can review now.

**Comment by jsf9k** [comment]
> Looks good. I'm confident that when the tests pass this will still be a good PR.

I find your surfeit of faith disturbing, @felddy!

**Review by mcdonnnj — APPROVED** [review]
Lookin' good. 👍

**Review by dav3r — COMMENTED** [review]
👍 (better late than never)

**Pull request merged**
