### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by jsf9k**
## 🗣 Description

This pull request updates this Ansible role in a few spots.  It removes some now-unnecessary code and switches the `upgrade` parameter for the `apt` Ansible module from `dist` to `full`.  The latter probably makes no difference, but `full` appears to be preferred now.

## 💭 Motivation and Context

I was looking at this Ansible role while debugging [a failed AMI build](https://github.com/cisagov/kali-packer/runs/1329005857?check_suite_focus=true), and I realized that it could use some updating.

## 🧪 Testing

All pre-commit hooks and molecule tests pass.

## 🚥 Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (causes existing functionality to change)
- [x] Clean up

## ✅ Checklist

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by dav3r — APPROVED** [review]
Nice and tidy. 👍

**Review by hillaryj — APPROVED** [review]
🥇

**Review by mcdonnnj — APPROVED** [review]
It slices, it dices~

**Comment by jsf9k** [comment]
This PR actually did make a difference.  [This build](https://github.com/cisagov/kali-packer/runs/1329005857?check_suite_focus=true) was failing without the change, but it passes with this change.

**Pull request merged**
